# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: assets/favicon.ico

# Personal info
name: Charlie Davidson
title: Senior Digital Project Manager
email: csg.davidson<at>gmail<dot>com
description: Hi! I’m Charlie Davidson. An Oxfordshire based, Senior Digital Project Manager. 
lang: en_gb
url: https://charliedavidson.co.uk

darkmode: false

# Google Tag Manager
gtm: "GTM-PQSN536"

# About Section
about_profile_image: assets/charlie.jpg
about_content:
  Hi, I'm <mark>Charlie Davidson</mark>. A Senior Digital Project Manager based in Bicester, Oxfordshire. From Cromarty, I went to Fortrose Academy and graduated with honours from Stirling University.<br><br>
  I've been a <mark>Digital Project Manager</mark> for twelve years and enjoy facilitating teams, building solutions, and refining processes. The following are areas where I can typically add value.<br> 
    - Bridging the gap between Project and Account Management
    - Agile adoption in the agency business model
    
# Projects Section
projects_title: Certifications

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about experience section title)

# More Section
more_title: Writing
more_content: | # this will include new lines to allow paragraphs
  I  write for websites that focus on digital product development, project management, and agile delivery. You can find links to the articles I've written below. 
    - <a href="https://www.girlsguidetopm.com/t-shaped-project-manager/" target="_blank">Make an impact as a T-Shaped project manager</a> - GirlsGuideToPM.com
    - <a href="https://projectbliss.net/how-to-be-a-great-scrum-master-servant-leader/" target="_blank">Scrum Master Servant Leader: 12 Ways To Move Your Team to Greatness</a> - Project Bliss
    - <a href="https://www.liquidplanner.com/blog/productive-pm-5-practical-systems-to-get-more-done/" target="_blank">Productive PM: 5 Practical Systems to Get More Done</a> - LiquidPlanner

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
