# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Charlie Davidson
title: Senior Digital Project Manager
email: csg.davidson<at>gmail.com

darkmode: false

# Google Tag Manager
gtm: "GTM-PQSN536"

# About Section
about_profile_image: charlie.jpg
about_content:
  Hi, I'm <mark>Charlie Davidson</mark>. A Senior Digital Project Manager and Scrum Master from Bicester, Oxfordshire.
  Raised in Cromarty, I went to Fortrose Academy and graduated with honours from Stirling University.
  I've been a <mark>Digital Project Manager</mark> for eleven years and enjoy facilitating teams, building solutions, and refining process.
    
# Projects Section
projects_title: Certifications

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about experience section title)

# More Section

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
