# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: assets/favicon.ico

# Personal info
name: Charlie Davidson
title: Digital Agency Operations
email: csg.davidson@gmail.com
website: https://charliedavidson.co.uk/
description: Hi! I’m Charlie Davidson. A digital professional specialising in digital agency project management and operations in Oxfordshire. 
lang: en
url: https://charliedavidson.co.uk

darkmode: false

# About Section
about_profile_image: assets/charlie.jpg
about_content:
  Hi, I'm <mark>Charlie Davidson</mark>. A digital professional based in Bicester, Oxfordshire. From Cromarty, I went to Fortrose Academy and graduated with honours from Stirling University.<br><br>
  A trained <mark>Digital Project Manager</mark> with fifteen years of experience; I enjoy facilitating teams, building solutions, and refining processes. <br><br>
  In recent years I’ve had success introducing and scaling <mark>agile delivery</mark> in the digital agency environment, from sales through to project delivery. <br><br>
  In 2023 I moved away from day-to-day Project Management into a broader coaching and oversight role. I sit on the GrowCreate Group Senior Management Team, with overall responsibility for company operations.
# Projects Section
projects_title: Certifications

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about experience section title)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
