# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: assets/favicon.ico

# Personal info
name: Charlie Davidson
title: Senior Digital Project Manager
email: csg.davidson<at>gmail.com
description: Hi! I’m Charlie Davidson. An Oxfordshire based, Senior Digital Project Manager and Scrum Master. 
lang: en_gb
url: https://charliedavidson.co.uk

darkmode: false

# Google Tag Manager
gtm: "GTM-PQSN536"

# About Section
about_profile_image: assets/charlie.jpg
about_content:
  Hi, I'm <mark>Charlie Davidson</mark>. A Senior Digital Project Manager and Scrum Master based in Bicester, Oxfordshire.
  From Cromarty, I went to Fortrose Academy and graduated with honours from Stirling University.
  I've been a <mark>Digital Project Manager</mark> for eleven years and enjoy facilitating teams, building solutions, and refining process.
    
# Projects Section
projects_title: Certifications

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about experience section title)

# More Section
more_title: Writing
more_content: | # this will include new lines to allow paragraphs
  I occasionally write for other websites that focus on project management, digital delivery, and agile delivery methods such as Scrum. You can find links to each of my articles below. 
    - <a href="https://www.girlsguidetopm.com/t-shaped-project-manager/" target="_blank">Make an impact as a T-Shaped project manager</a> - GirlsGuideToPM.com

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
